name: Run flow tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.25", "1.26", "1.27"]

    steps:
      - uses: actions/checkout@v6
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: |
          go mod tidy
      - name: Report suspicious constructs
        run: |
          make vet
      - name: Run go unit tests
        run: |
          make test
